import { useState, useEffect, useCallback } from 'react';
import { Calendar, MapPin, ExternalLink, GraduationCap, Wrench, Mic, Building, DollarSign, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";

const manualEvents = [
  {
    type: ["Conference"],
    title: "Kanban Community Meetup in Prague",
    date: new Date("2026-03-06"),
    displayDate: "Mar 6, 2026",
    time: "9:00 AM - 5:00 PM CET",
    location: "Prague, Rowing Club Slavia Prague",
    price: "€40 early bird (until Feb 6), €50 regular",
    description: `Join us for an exciting day of learning, sharing, and connecting with the Kanban community in Prague! Whether you're completely new to Kanban or an experienced practitioner, this meetup is designed for you!

    This is an OpenSpace event, meaning you shape the agenda! Bring your questions, challenges, ideas, and topics, and we'll explore them together. With many experienced ProKanban Trainers on site, you'll have access to world-class expertise in an informal, collaborative setting.

    In between the participant-led discussions, you'll hear lightning talks from a few selected speakers.`,
    ctaText: "Register",
    ctaLink: "https://www.prokanban.org/kanban-community-event",
    source: "manual"
  },
];

const EventsSection = () => {
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Manual events - these will always be included
  // const manualEvents = [

  const fetchEvents = useCallback(async () => {
    try {
      setLoading(true);
      
      // Fetch from events.json file (generated by GitHub Actions)
      const response = await fetch('/events-data.json');
      
      if (!response.ok) {
        throw new Error('Could not load external events');
      }
      
      const externalData = await response.json();
      
      // Parse dates and combine with manual events
      const externalEvents = externalData.events.map(event => ({
        ...event,
        date: new Date(event.date)
      }));

      // Combine all events
      const allEvents = [
        ...manualEvents,
        ...externalEvents
      ];

      // Filter out past events and sort by date
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      
      const upcomingEvents = allEvents
        .filter(event => event.date >= today)
        .sort((a, b) => a.date - b.date);

      setEvents(upcomingEvents);
      setError(null);
    } catch (err) {
      console.error('Error fetching events:', err);
      setError('External events could not be loaded. Showing manual events only.');
      // Fall back to manual events only
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      setEvents(manualEvents.filter(event => event.date >= today));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchEvents();
  }, [fetchEvents]);

  const getTypeIcon = (type) => {
    switch (type) {
      case "Training":
        return <GraduationCap className="h-4 w-4" />;
      case "Workshop":
        return <Wrench className="h-4 w-4" />;
      case "Talk":
        return <Mic className="h-4 w-4" />;
      case "Conference":
        return <Building className="h-4 w-4" />;
      default:
        return null;
    }
  };

  return (
    <section id="events" className="py-20 bg-background">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-5xl font-bold text-foreground mb-6">
            See us{" "}
            <span className="bg-gradient-primary bg-clip-text text-transparent">
              Live!
            </span>{" "}
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            Join our public workshops, trainings, or meet us at conferences.
          </p>
        </div>

        {/* Error Alert */}
        {error && (
          <Alert className="mb-8">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {/* Loading State */}
        {loading && (
          <div className="text-center py-12">
            <div className="inline-block h-8 w-8 animate-spin rounded-full border-4 border-solid border-primary border-r-transparent"></div>
            <p className="mt-4 text-muted-foreground">Loading events...</p>
          </div>
        )}

        {!loading && events.length === 0 && (
          <div className="text-center py-12">
            <p className="text-muted-foreground">No upcoming events at the moment. Check back soon!</p>
          </div>
        )}

        {!loading && events.length > 0 && (
          /* Events Grid */
          <div className="grid lg:grid-cols-3 gap-8 mb-16">
            {events.map((event, index) => (
              <Card key={`${event.source}-${index}`} className="group hover:shadow-medium transition-all duration-300 border-0 shadow-soft">
                <CardHeader className="pb-4">
                  <div className="flex items-center mb-2 gap-2 flex-wrap">
                    {Array.isArray(event.type) ? (
                      event.type.map((type) => (
                        <Badge key={type} variant="outline" className="text-primary border-primary flex items-center gap-1">
                          {getTypeIcon(type)}
                          {type}
                        </Badge>
                      ))
                    ) : (
                      <Badge variant="outline" className="text-primary border-primary flex items-center gap-1">
                        {getTypeIcon(event.type)}
                        {event.type}
                      </Badge>
                    )}
                  </div>

                  <CardTitle className="text-xl font-bold text-foreground group-hover:text-primary transition-colors">
                    {event.title}
                  </CardTitle>

                  <CardDescription className="text-muted-foreground">
                    {event.description}
                  </CardDescription>
                </CardHeader>

                <CardContent className="space-y-4">
                  <div className="space-y-3">
                    <div className="flex items-center text-sm text-muted-foreground">
                      <Calendar className="h-4 w-4 mr-3 text-primary" />
                      {event.displayDate}
                    </div>

                    {/* time intentionally omitted: show only date */}

                    <div className="flex items-center text-sm text-muted-foreground">
                      <MapPin className="h-4 w-4 mr-3 text-primary" />
                      {event.location}
                    </div>

                    {event.price && (
                      <div className="flex items-center text-sm text-muted-foreground">
                        <DollarSign className="h-4 w-4 mr-3 text-primary" />
                        {event.price}
                      </div>
                    )}
                  </div>

                  <Button
                    variant="default"
                    className="w-full group"
                    asChild
                  >
                    <a href={event.ctaLink} target="_blank" rel="noopener noreferrer">
                      {event.ctaText}
                      <ExternalLink className="ml-2 h-4 w-4 group-hover:translate-x-1 transition-transform" />
                    </a>
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>
    </section>
  );
};

export default EventsSection;