import { useState, useEffect } from 'react';
import { Calendar, Clock, MapPin, ExternalLink, GraduationCap, Wrench, Mic, Building, DollarSign, Star, MessageCircle, AlertCircle, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";

const EventsSection = () => {
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [lastUpdated, setLastUpdated] = useState(null);

  // Manual events - these will always be included
  const manualEvents = [
    /*{
      type: ["Workshop"],
      title: "🚀 Probabilistic Forecasting at Scale",
      date: new Date("2025-11-18"),
      displayDate: "Nov 18, 2025",
      time: "1:00 PM - 5:00 PM CET",
      location: "Online (Zoom)",
      price: "150€ (Early Bird), 200€ (Regular)",
      description: `A hands-on workshop introducing a practical, data-driven approach to forecasting delivery using Monte Carlo simulations at the portfolio level. Learn to right-size Features and Epics to make them forecastable, run forecasts across multiple teams, and understand how dependencies influence predictability and risk.
      
      The workshop includes 1 month of Lighthouse Premium License, 1-hour consulting session with an expert trainer, and a 10% discount if you join our Applying Scaled Portfolio Kanban (ASPK) training.`,
      ctaText: "Buy Tickets",
      ctaLink: "https://www.tickettailor.com/events/letpeoplework/1891877",
      source: "manual"
    },*/
  ];

  useEffect(() => {
    fetchEvents();
  }, []);

  const fetchEvents = async () => {
    try {
      setLoading(true);
      
      // Fetch from events.json file (generated by GitHub Actions)
      const response = await fetch('/events-data.json');
      
      if (!response.ok) {
        throw new Error('Could not load external events');
      }
      
      const externalData = await response.json();
      
      // Parse dates and combine with manual events
      const externalEvents = externalData.events.map(event => ({
        ...event,
        date: new Date(event.date)
      }));

      // Combine all events
      const allEvents = [
        ...manualEvents,
        ...externalEvents
      ];

      // Filter out past events and sort by date
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      
      const upcomingEvents = allEvents
        .filter(event => event.date >= today)
        .sort((a, b) => a.date - b.date);

      setEvents(upcomingEvents);
      setLastUpdated(new Date(externalData.lastUpdated));
      setError(null);
    } catch (err) {
      console.error('Error fetching events:', err);
      setError('External events could not be loaded. Showing manual events only.');
      // Fall back to manual events only
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      setEvents(manualEvents.filter(event => event.date >= today));
    } finally {
      setLoading(false);
    }
  };

  const getTypeIcon = (type) => {
    switch (type) {
      case "Training":
        return <GraduationCap className="h-4 w-4" />;
      case "Workshop":
        return <Wrench className="h-4 w-4" />;
      case "Talk":
        return <Mic className="h-4 w-4" />;
      case "Conference":
        return <Building className="h-4 w-4" />;
      default:
        return null;
    }
  };

  return (
    <section id="events" className="py-20 bg-background">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-5xl font-bold text-foreground mb-6">
            See us{" "}
            <span className="bg-gradient-primary bg-clip-text text-transparent">
              Live!
            </span>{" "}
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            Join our public workshops, trainings, or meet us at conferences.
          </p>
          {lastUpdated && (
            <p className="text-sm text-muted-foreground mt-4 flex items-center justify-center gap-2">
              <RefreshCw className="h-3 w-3" />
              Events updated: {lastUpdated.toLocaleString()}
            </p>
          )}
        </div>

        {/* Error Alert */}
        {error && (
          <Alert className="mb-8">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {/* Loading State */}
        {loading ? (
          <div className="text-center py-12">
            <div className="inline-block h-8 w-8 animate-spin rounded-full border-4 border-solid border-primary border-r-transparent"></div>
            <p className="mt-4 text-muted-foreground">Loading events...</p>
          </div>
        ) : events.length === 0 ? (
          <div className="text-center py-12">
            <p className="text-muted-foreground">No upcoming events at the moment. Check back soon!</p>
          </div>
        ) : (
          /* Events Grid */
          <div className="grid lg:grid-cols-3 gap-8 mb-16">
            {events.map((event, index) => (
              <Card key={`${event.source}-${index}`} className="group hover:shadow-medium transition-all duration-300 border-0 shadow-soft">
                <CardHeader className="pb-4">
                  <div className="flex items-center mb-2 gap-2 flex-wrap">
                    {Array.isArray(event.type) ? (
                      event.type.map((type) => (
                        <Badge key={type} variant="outline" className="text-primary border-primary flex items-center gap-1">
                          {getTypeIcon(type)}
                          {type}
                        </Badge>
                      ))
                    ) : (
                      <Badge variant="outline" className="text-primary border-primary flex items-center gap-1">
                        {getTypeIcon(event.type)}
                        {event.type}
                      </Badge>
                    )}
                  </div>

                  <CardTitle className="text-xl font-bold text-foreground group-hover:text-primary transition-colors">
                    {event.title}
                  </CardTitle>

                  <CardDescription className="text-muted-foreground">
                    {event.description}
                  </CardDescription>
                </CardHeader>

                <CardContent className="space-y-4">
                  <div className="space-y-3">
                    <div className="flex items-center text-sm text-muted-foreground">
                      <Calendar className="h-4 w-4 mr-3 text-primary" />
                      {event.displayDate}
                    </div>

                    {event.time && (
                      <div className="flex items-center text-sm text-muted-foreground">
                        <Clock className="h-4 w-4 mr-3 text-primary" />
                        {event.time}
                      </div>
                    )}

                    <div className="flex items-center text-sm text-muted-foreground">
                      <MapPin className="h-4 w-4 mr-3 text-primary" />
                      {event.location}
                    </div>

                    {event.price && (
                      <div className="flex items-center text-sm text-muted-foreground">
                        <DollarSign className="h-4 w-4 mr-3 text-primary" />
                        {event.price}
                      </div>
                    )}
                  </div>

                  <Button
                    variant="default"
                    className="w-full group"
                    asChild
                  >
                    <a href={event.ctaLink} target="_blank" rel="noopener noreferrer">
                      {event.ctaText}
                      <ExternalLink className="ml-2 h-4 w-4 group-hover:translate-x-1 transition-transform" />
                    </a>
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        )}

        {/* CTA Section */}
        <div id="custom-events" className="text-center bg-gradient-subtle rounded-2xl p-12 border border-border">
          <div className="flex justify-center mb-6">
            <div className="bg-primary/10 rounded-full p-4">
              <MessageCircle className="h-8 w-8 text-primary" />
            </div>
          </div>
          
          <h3 className="text-3xl font-bold text-foreground mb-6">
            Need Something Tailored to{" "}
            <span className="bg-gradient-primary bg-clip-text text-transparent">
              Your Needs?
            </span>
          </h3>
          
          <p className="text-lg text-muted-foreground mb-8 max-w-3xl mx-auto">
            We believe in the power of collaboration. This is why all our trainings, workshops, and consulting services are designed together with you to match your needs.
            Furthermore, we always deliver them in pairs, so you get the best insights and diverse perspectives.
          </p>

          <div className="grid md:grid-cols-2 gap-6 max-w-4xl mx-auto mb-10">
            <div className="bg-background/50 rounded-xl p-6 border border-border/50">
              <div className="flex items-center justify-center mb-4">
                <Star className="h-6 w-6 text-primary mr-2" />
                <h4 className="text-lg font-semibold text-foreground">Custom Training & Private Workshops</h4>
              </div>
              <p className="text-muted-foreground text-sm">
                Didn't find exactly what you're looking for? We create bespoke training programs and private workshops tailored to your team's specific needs and challenges. Get exclusive attention for your team with our expert pairs delivering maximum impact.
              </p>
            </div>
            
            <div className="bg-background/50 rounded-xl p-6 border border-border/50">
              <div className="flex items-center justify-center mb-4">
                <DollarSign className="h-6 w-6 text-primary mr-2" />
                <h4 className="text-lg font-semibold text-foreground">Pricing</h4>
              </div>
              <p className="text-muted-foreground text-sm">
                Private events start at $1,000 per event (not per attendee). Perfect for teams of up to 30 people looking for focused, collaborative learning experiences.
              </p>
            </div>
          </div>

          <Button variant="hero" size="lg" asChild>
            <a href="mailto:contact@letpeople.work">
              <MessageCircle className="mr-2 h-5 w-5" />
              Reach Out To Talk About How We Can Support
            </a>
          </Button>
        </div>
      </div>
    </section>
  );
};

export default EventsSection;